apps/views/frontend.py
from flask import Flask, Blueprint, render_template, \
					g, url_for, session, request, flash, \
					redirect
from flask.ext.login import login_required, \
					current_user, login_required,\
					fresh_login_required
from apps.forms import SuggestionForm, EditForm, SearchProblemForm
frontend = Blueprint('frontend', __name__, 
					static_folder = 'static',
					template_folder = 'templates')
from apps import models, app, db
					
@frontend.before_request
def before_request() :
	g.user = current_user
					
@frontend.route('/')
@frontend.route('/index/')
def index():
	# if '_fresh' in session :
		# print session['_fresh']
	# if 'user' in session : 
		# print session['user']
	
	form = SearchProblemForm()
	categories = models.Subject.query.order_by('name')
	nameOfCategories = []
	for x in categories :
		nameOfCategories.append((x.id, x.name))
	form.subject.choices = nameOfCategories
	typeOfTimeDelta = []
	for x, y in app.config['TIMEDELTA_CHOICE'] :
		typeOfTimeDelta.append((x, y))
	form.timeDelta.choices = typeOfTimeDelta
	form.timeDelta.data = app.config['DEFAULT_TIME_DELTA']
	
	docs = models.Document.query.all()
	numberOfDocuments = len(docs)
	users = models.User.query.all()
	numberOfUser = len(users)
	
	listOfRecentDocument = models.Document.query.\
								limit(numberOfDocuments).from_self().\
								order_by(models.Document.timeStamp)
	listOfRecentDocument = list(listOfRecentDocument)
	resultlist = []
	for i in range(len(listOfRecentDocument) - 1, -1, -1) :
		doc = listOfRecentDocument[i]
		if doc.author.isAdmin :
			resultlist.append(doc)
			if len(resultlist) > 5 :
				break
	
	return render_template('frontend/index.html', 
							form = form,
							numberOfDocuments = numberOfDocuments,
							numberOfUser = numberOfUser,
							listOfRecentDocument = resultlist)
	
@frontend.route('/details')
@login_required
def details():
	uid = current_user.id
	u = models.User.query.filter(models.User.id == uid).first()
	docs = []
	for x in u.contributions :
		docs.append(x)
	doc = models.Document.query.filter(models.Document.id == u.lastVisit).first()
	
	return render_template('frontend/details.html', 
							titile = 'Home', 
							username = u.username, 
							docs = docs,
							doc = doc)

@frontend.route('/details/<int:uid>')
def otherUserDetails(uid):
	u = models.User.query.filter(models.User.id == uid).first()
	if u == None :
		flash(app.config['HOWDOYOUFINDTHISPAGE'])
		return redirect(url_for('frontend.index'))
	
	docs = []
	for x in u.contributions :
		docs.append(x)
	doc = models.Document.query.filter(models.Document.id == u.lastVisit).first()
	
	return render_template('frontend/details.html', 
							titile = 'Home', 
							username = u.username, 
							docs = docs,
							doc = doc)
	
@frontend.route('/FAQ', methods = ['POST', 'GET'])
def faq() :
	form = SuggestionForm()
	# print '#######\n\n\n\n  here'
	# print '###', form.suggestion.data
	return render_template('frontend/faq.html', form = form)

@frontend.route('/Thank', methods = ['POST', 'GET'])
def suggest() :
	flash('Having receive!!!')
	return render_template('frontend/index.html')

@frontend.route('/edit', methods = ['POST', 'GET'])
# @login_required
@fresh_login_required
def changeUserDetails() :
	user = current_user
	form = EditForm()
	u = models.User.query.filter(models.User.id == user.id).first()
	
	if not form.username.data :
		form.username.data = u.username
	if not form.email.data :
		form.email.data = u.email
	
	# print 'form.validate_on_submit:', form.validate_on_submit()
	if request.method == 'POST' and form.validate_on_submit() :
		# print 'xxxxxxx'
		if u.password == form.password.data :
			u.username = form.username.data
			print form.newPassword.data
			if len(form.newPassword.data) > 0 :
				u.password = form.newPassword.data
			u.email = form.email.data
			flash('Succefully change!!')
			db.session.commit()
			# print 'yyyyy'
			return redirect(url_for('frontend.changeUserDetails'))
		else :
			# print 'xxxxx'
			flash(app.config['PASSWROD_NOT_MATCH'])
	
	return render_template('frontend/changeUserDetails.html', form = form)

apps/views/processProblems.py
# -*- coding: utf-8 -*-

from flask import Flask, request, session, \
					g, redirect, url_for, \
					abort, render_template, flash,  \
					Blueprint
from flask.ext.login import current_user, login_required
from apps import app, db, models
from apps.forms import SearchProblemForm, ProblemForm, BrushForm, ChoiceForm,\
						UploadForm
import datetime, re
import flask.ext.whooshalchemy
from apps.models import MyOperateError
from processMethods import *

processProblems = Blueprint('processProblems', __name__, 
					static_folder = 'static',
					template_folder = 'templates')

@processProblems.route('/search', methods=['GET', 'POST'])
def search() :
	print 'search begin'
	form = SearchProblemForm()
	categories = models.Subject.query.order_by('name')
	
	nameOfCategories = []
	for x in categories :
		nameOfCategories.append((x.id, x.name))
	form.subject.choices = nameOfCategories
	
	typeOfTimeDelta = []
	for x, y in app.config['TIMEDELTA_CHOICE'] :
		typeOfTimeDelta.append((x, y))
	form.timeDelta.choices = typeOfTimeDelta
	if request.method == 'GET' :
		form.timeDelta.data = app.config['DEFAULT_TIME_DELTA']
	
	print 'search fine'
	# print 'data:', form.timeDelta.data
	
	if request.method == 'POST' and form.validate_on_submit() :
		name = 'allproblems'
		showAll = 1
		if form.filename.data :
			name = form.filename.data
			showAll = 0
		print 'name:', name
		# print len(name)
		category = form.subject.data
		timeDelta = form.timeDelta.data
		# print 'Good'
		return redirect(url_for('processProblems.showResult', \
								category = category, 
								name = name, \
								timeDelta = timeDelta, \
								showAll = showAll))
	
	docs = models.Document.query.all()
	numberOfDocuments = len(docs)
	listOfRecentDocument = models.Document.query.\
								limit(numberOfDocuments).from_self().\
								order_by(models.Document.timeStamp)
	listOfRecentDocument = list(listOfRecentDocument)
	listOfRecentDocument.reverse()
	listOfRecentDocument = listOfRecentDocument[0:7]
	
	return render_template('processProblems/search.html', 
							title = u'Select your want!',
							form = form,
							listOfRecentDocument = listOfRecentDocument)

@processProblems.route('/show/<string:name>&<int:category>\
						&<int:timeDelta>&<int:showAll>', \
						methods = ['GET'])
def showResult(category, name, timeDelta, showAll = 0) :
	print timeDelta
	timeDelta = app.config['TIMEDELTA'][timeDelta]
	startTime = datetime.datetime.utcnow() - timeDelta
	print datetime.datetime.utcnow()
	print timeDelta
	print startTime
	if showAll == 0 :
		result = models.Document.query.\
					filter(models.Document.timeStamp >= startTime).\
					filter(models.Document.subjectId == category).\
					whoosh_search(name, limit = 50).all()
	else :
		result = models.Document.query.\
					filter(models.Document.timeStamp >= startTime).\
					filter(models.Document.subjectId == category).all()
	result = list(result)
	
	return render_template('processProblems/showresult.html', result = result)

@processProblems.route('/show/<did>', methods = ['GET', 'POST'])
def show(did) :
	print 'yyyyyyyyyyyyyyyyyy'
	
	# print 'request.form:', request.form
	allCorret = False
	
	# 定义表格
	if 'allProblem' not in dir() :
		# print 'not define'
		# print did
		# print session
		try :
			documentId = int(did)
		except Exception as e :
			flash(app.config['HOWDOYOUFINDTHISPAGE'])
			return redirect(url_for('processProblems.search'))
		
		try :
			if documentId < 6666666 :
				doc = models.Document.query.filter(\
									models.Document.id == documentId\
									).first()
				print 'doc,', doc
				if doc is None :
					raise Exception(app.config['HOWDOYOUFINDTHISPAGE'])
			else :
				documentId = session['tempfile']
				doc = models.Document.query.filter(\
									models.Document.id == documentId\
									).first()
				if doc is None :
					raise Exception(app.config['NOSUCHFILE'])
				pros = []
				for pro in doc.problems :
					pros.append((pro.content, pro.choice, pro.answer))
				tempfile = models.Tempfile(doc.title, pros)
				g.doc = tempfile
		except Exception as e :
			print e
			flash(e.message)
			print 'hello'
			return redirect(url_for('processProblems.search'))
		allProblem = getAllProblem(doc)
	
	# 将传过来的表单填写入对应的表格位置
	userLogin = ('user' in session and session['user'] == current_user.id)
	userLastSubmitDict = {}
	# 获取用户上次提交的答案
	if userLogin :
		u = models.User.query.filter(\
									models.User.id == current_user.id\
									).first()
		if u.lastVisit == documentId :
			# print u.lastSubmit
			tmpAnswer = u.lastSubmit.split('##')
			print 'dddd'
			print tmpAnswer
			temp = []
			for x in tmpAnswer :
				if len(x) > 0 :
					temp.append(x)
			tmpAnswer = temp
			length = len(tmpAnswer) / 2
			for i in range(0, length) :
				print int(tmpAnswer[2 * i]), unicode(tmpAnswer[2 * i + 1])
				userLastSubmitDict[int(tmpAnswer[2 * i])] = unicode(tmpAnswer[2 * i + 1])
	
	if request.method == 'POST' :
		print 'POST'
		doc.countUsed += 1
		recordUserId = documentId
		recordUserAnswer = ''
		for pro in allProblem.pro :
			# print pro.index
			userChoices_list = request.form.getlist(str(pro.index))
			# print pro.index, userChoices_list
			# if len(userChoices_list) < 1 and userLogin :
				# if userLastSubmitDict.has_key(pro.index) :
					# userChoices_list = userLastSubmitDict[pro.index]
			
			tmpAnswer = ''
			if len(userChoices_list) > 0 :
				print userChoices_list
			for c in userChoices_list :
				index = ord(c) - ord('A')
				# pro.choices[index].option.checked = True
				pro.choices[index].option.data = True
				tmpAnswer += c
			
			if len(tmpAnswer) > 0 :
				# print tmpAnswer
				recordUserAnswer += unicode(pro.index) + "##"
				recordUserAnswer += tmpAnswer + "##"
		
		try :
			# print 'userLogin', userLogin
			# print 'recordUserId', recordUserId
			# print 'recordUserAnswer', recordUserAnswer
			if userLogin and len(recordUserAnswer) > 0 :
				u = models.User.query.filter(\
									models.User.id == current_user.id\
									).first()
				u.lastVisit = recordUserId
				u.lastSubmit = recordUserAnswer
				db.session.commit()
				# print 'record:', recordUserAnswer
		except Exception as e :
			print 'error', e
			pass
	elif userLogin :
		for pro in allProblem.pro :
			# print pro.index
			userChoices_list = ''
			if userLastSubmitDict.has_key(pro.index) :
				userChoices_list = userLastSubmitDict[pro.index]
			for c in userChoices_list :
				index = ord(c) - ord('A')
				pro.choices[index].option.data = True
	
	# 检查答案，给予反馈
	if allProblem.validate_on_submit() and myValidate(allProblem.pro) :
		allCorret = True
		for pro in allProblem.pro :
			ret = checkAnswer(pro, allCorret)
			pro = ret[0]
			allCorret = ret[1]
	
	print 'how allproblems:', 'allProblem' in dir()
	if allCorret == False :
		return render_template('processProblems/showproblems.html', 
								index = did, papers = allProblem)
	else :
		return render_template('processProblems/congratulation.html')

def addSessionTempFile(x) :
	if 'tempfile' in session :
		try :
			docId = session['tempfile']
			if docId != x :
				doc = models.Document.query.filter(\
											models.Document.id == docId\
											).first()
				db.session.delete(doc)
				db.session.commit()
		except Exception as e :
			print 'No such file'
		
		session.pop('tempfile', None)
	session['tempfile'] = x
	# print session
		
@processProblems.route('/upload', methods = ['GET', 'POST'])
@login_required
def upload() :
	if 'form' not in dir() :
		form = UploadForm()
		categories = models.Subject.query.order_by('name')
		nameOfCategories = []
		for x in categories :
			nameOfCategories.append((x.id, x.name))
		form.subject.choices = nameOfCategories
	
	
	# if 'form' in dir() :
		# print 'hhhhhhh'
		# print form.validate_on_submit()
		# print form.subject.data
		# print form.subject.choices
		# print form.filename.data
		# print form.file.data
		# print request.method
		# print form.errors
	
	if request.method == 'POST' :
		if form.validate_on_submit() :
			# print "here"
			try :
				
				title = form.filename.data
				title = title.title()
				# print title
				content = form.file.data
				# print 'content:', content
				# print ord(content[24])
				answer = None
				if form.answer.data :
					answer = form.answer.data
				category = form.subject.data
				
				print 'begin change'
				format_content = change(content, answer)
				print 'end change'
	#			format_content should be a pair list
	#			the first element should be problem's description
	#			the second element should be problem's answer
				
				# print format_content
				# for x, y, z in format_content :
					# print x.encode('gb2312'), y.encode('gb2312'), z.encode('gb2312')
				
				if len(format_content) < 2 :
					raise MyOperateError('The number of problems is too small. \
											Only %d problems found' % \
											(len(format_content)))
				
				
				# print 'fine'
				
				doc = models.Document(title = title, \
										author = current_user, \
										subjectId = category)
				db.session.add(doc)
				db.session.commit()
				for content, choices, answer in format_content :
					pro = models.Problem(source = doc, \
										content = content, \
										choice = choices, \
										answer = answer)
					db.session.add(pro)
				db.session.commit()
				
				flash(app.config['SUCCESS_PROCESS'])
				if current_user.isAdmin == True :
					return redirect(url_for('processProblems.show', 
									did = unicode(doc.id)))
				else :
					# print session
					addSessionTempFile(doc.id)
					# print session
					# print title
					# print 'session:', session['tempfile'][0]
					return redirect(url_for('processProblems.show', 
									did = unicode(6666666)))
			except MyOperateError as e:
				print '\n\n\n xxx :', e.description
				print '\r\n\r\n\r\n\r\n\r\n\r\n\r\n\n'
				flash(app.config['FAIL_PROCESS'])
			except Exception as e:
				print '\n\n\n yyy :', e
				print '\r\n\r\n\r\n\r\n\r\n\r\n\r\n\n'
				flash(app.config['FAIL_PROCESS'])
		else :
			if current_user.isAdmin :

apps/templates/processProblems/congratulation.html
{% extends "mainpage.html" %}

{% block metas %}
  {{ super() }}
  <meta http-equiv="refresh" content="3;url={{ url_for('processProblems.search') }}">
{% endblock %}

{% block content %}
  <p>学神，你的答案全部正确！</p>
  <p>快去做下一篇题目吧！</p><br/>
  <hr/>
  <p>三秒后自动跳转至搜索页面。</p>
  <span class="glyphicons glyphicons-thumbs-up"></span>
{% endblock %}

apps/templates/processProblems/search.html
{% extends "mainpage.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block someerrors %}
  {% if form.errors %}
    <div>
      <p>有点错误：</p>
      {{wtf.form_errors(form, hiddens = "False")}}
    </div>
    <hr/>
  {% endif %}
{% endblock %}

{% block content %}
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-6 pull-left">
        <h2>最新题目：</h2><br/>
        <table id = "my-show-table">
          <tr>
            <th width = "50%"><h4>试卷名</h4></th>
            <th width = "30%"><h4>上传者</h4></th>
            <th width = "20%"><h4>使用次数</h4></th>
          </tr>
          
          {% for doc in listOfRecentDocument %}
            <tr>
              <td>
                <a href = "{{url_for('processProblems.show', did = doc.id)}}">{{doc.title|safe}}</a>
              </td>
              <td>
                <p><a href = "{{url_for('frontend.otherUserDetails', uid = doc.author.id)}}">{{doc.author.username|safe}}（{% if not doc.author.isAdmin %}非{% endif %}管理员）</a></p>
              </td>
              <td>
                <p>{{doc.countUsed|safe}}</p>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
      <div class = "col-lg-6 pull-right" align = "middle">
        <h1>搜索</h1><br/>
        <div class = "form-group">
          <form action = "{{ url_for('processProblems.search') }}" 
                method = "post" name = "login">
            {{ form.hidden_tag() }}
            <p>科目： {{ form.subject(class = "my-input-field")|safe }} </p> <br/>
            <p>文件名称关键字：<br/>{{ form.filename(class = "my-input-field", placeholder = "不填将显示所有题目")|safe }}</p><br/>
            <p>时间段：<br/>{{ form.timeDelta(class = "my-input-field")|safe }}</p><br/>
            <!--<button type = "submit" class="btn btn-default">{{ form.submit(value = "我选好了") }}</button>
            {{ form.submit(value = "我选好了") }}-->
            {{ wtf.form_field(form.submit, value = "开始查找")|safe }}<br/>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/templates/processProblems/showproblems.html
{% extends "mainpage.html" %}

{% block someerrors %}
  {% for eachpro in papers.pro %}
    {% if eachpro.errors %}
    <div>
      <p>Problem {{eachpro.index}} has some wrongs :</p>
      <ul>
        {% for error in eachpro.errors %}
          <li> {{error}} </li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  {% endfor %}
{% endblock %}

{% block html_attribs %}
  style = "padding-bottom: 70px;"
{% endblock %}

{% block otherNavbar %}
  <div class = "navbar navbar-default navbar-fixed-bottom">
    <div class = "container">
      <div class = "navbar-inner">
        <div class = "navbar-left">
          <button id = "my-button-toTop" type = "button" class = "btn btn-default">飞到顶部</button>
          <button id = "my-button-toBottom" type = "button" class = "btn btn-default">飞到底部</button>
        </div>
        <div class = "navbar-right">
          <button id = "my-button-hide-correct" type = "button" class = "btn btn-default">隐藏正确题目</button>
          <button id = "my-button-submit-my-problem-form" class = "btn btn-default">提交试卷</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div id = "my-rightclick-menu" style = "display:none;">
    <ul id = "my-rightclick-list">
      <li><button id = "my-button-cheat" type = "button" class = "btn btn-default">作弊</button></li>
      <li><button id = "my-button-hideCheat" type = "button" class = "btn btn-default">藏起来</button></li>
      <li><button id = "my-button-hideAllCheat" type = "button" class = "btn btn-default">全藏起来</button></li>
    </ul>
  </div>


  <div class="page-header" align = "center" style="padding-top:70px;"><h1>{{ papers.title|safe }}</h1></div><br/>
  <form id = "my-show-problem-form" method = "POST" action = "{{ url_for('processProblems.show', did = index) }}">
    {{papers.hidden_tag()}}
    
    <div class = "form-controls">
      <ol type = 1 start = 1>
        {% for eachpro in papers.pro %}
          <li id = "my-problem-{{eachpro.index}}" style = "display: {% if eachpro.check == 2 and papers.hideCorrectProblem.data %} none {% endif %};" {% if eachpro.check == 2 %} canHide = "true" {% endif %}>
            <p class = "my-problem-description">{{eachpro.description|safe}}</p><br/>
            {% for x in eachpro.choices %}
              <p class = "my-problem-choice">{% if eachpro.singleSelect == True %}{{ x.option(type = 'radio')|safe }}{% else %}{{ x.option|safe }}{% endif %}{{ x.description|safe }}</p><br/>
            {% endfor %}
            {% if eachpro.check == 1 %}
              <span class = "label label-danger">{{ eachpro.message|safe }}</span><br/>
            {% elif eachpro.check == 2 %}
              <span class = "label label-success">{{ eachpro.message|safe }}</span><br/>
            {% endif %}
          </li><br/>
        {% endfor %}
      </ol>
    
    </div>
    <p>{{ papers.hideCorrectProblem(id = "my-hide-correct-checkbox") }} 隐藏正确题目，剩下错误和未做的题目。按右下部的按钮也一样。</p>
  </form>
{% endblock %}

apps/templates/processProblems/showresult.html
{% extends "mainpage.html" %}

{% block content %}
  <div id = "my-search-result" class = "container">
    {% if result|length > 0 %}
      <p>搜索结果如下:</p>
        <table>
          <tr>
            <td><h3>试卷名</h3></td>
            <td><h3>上传者</h3></td>
            <td><h3>使用次数</h3></td>
          </tr>
          
          {% for x in result %}
            <tr>
              <td>
                <a href = "{{url_for('processProblems.show', did = x.id)}}">{{x.title|safe}}</a>
              </td>
              <td>
                <p><a href = "{{url_for('frontend.otherUserDetails', uid = x.author.id)}}">{{x.author.username|safe}}（{% if not x.author.isAdmin %}非{% endif %}管理员）</a></p>
              </td>
              <td>
                <p>{{x.countUsed|safe}}</p>
              </td>
            </tr>
          {% endfor %}
        </table><br/>
        <p>共{{ result|length|safe }}个结果。</p><br/>
        <p>找不到？按<a href = "{{url_for('processProblems.search')}}">这里</a>返回调整查找参数。</p><br/>
    {% else %}
      <p>没有匹配结果。</p>
      <p>点击<a href = "{{url_for('processProblems.search')}}">这里</a>返回</p>
    {% endif %}
  </div>
{% endblock %}

apps/templates/processProblems/upload.html
{% extends "mainpage.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block someerrors %}
  {% if form.errors %}
    <div>
      <p>有点错误：</p>
      {{wtf.form_errors(form, hiddens = "False")}}
    </div>
    <hr/>
  {% endif %}
{% endblock %}

{% block content %}
  <button id = "my-button-problem-type-1" class = "btn btn-default" type = "button">答案在题目中</button>
  <button id = "my-button-problem-type-2" class = "btn btn-default" type = "button">答案在题目外</button><br/>
  <form id = "my-problem-form" method = "POST" action = "{{ url_for('processProblems.upload') }}" name = "upload">
<!--       <input type = "file" name = "problem"> -->
<!--       <hr/> -->
<!--       <input type = "submit" name = "submit" value = "submit" id = "submit"> -->
    {{form.hidden_tag()}}
    <hr/>
    <p>标题：</p><br/>
    {{form.filename(size = 50, placeholder = "标题将作为日后检索题目的文件名！")|safe}} <br/>
    <div id = "my-problem-content">
      <p>题目内容：</p><br/>
      {{form.file(rows = 10, cols = 100, placeholder = "直接粘帖题目即可，不支持图片。")|safe}} <br/>
    </div><br/>
    <div id = "my-problem-answer" style = "display: none;">
      <p>题目答案：</p><br/>
      {{form.answer(rows = 10, cols = 100, placeholder = "直接粘帖答案部分即可，不支持图片。")|safe}} <br/>
    </div>
    <p>分类：</p>{{form.subject(class = "my-input-field")|safe}} <br/>
    <hr/>
    <span style="color: red;">以上内容一旦提交<strong>不可更改</strong>。</span></p> 
    <hr/>
    {{form.submit(value = "提交")|safe}} <br/>
    <hr/>
  </form>
  
  <hr/>
  <h2><a href = "{{url_for('frontend.faq')}}">注意事项</a></h2>
{% endblock %}