apps/views/frontend.py
from flask import Flask, Blueprint, render_template, \
					g, url_for, session, request, flash, \
					redirect
from flask.ext.login import login_required, \
					current_user, login_required,\
					fresh_login_required
from apps.forms import SuggestionForm, EditForm, SearchProblemForm
frontend = Blueprint('frontend', __name__, 
					static_folder = 'static',
					template_folder = 'templates')
from apps import models, app, db
					
@frontend.before_request
def before_request() :
	g.user = current_user
					
@frontend.route('/')
@frontend.route('/index/')
def index():
	# if '_fresh' in session :
		# print session['_fresh']
	# if 'user' in session : 
		# print session['user']
	
	form = SearchProblemForm()
	categories = models.Subject.query.order_by('name')
	nameOfCategories = []
	for x in categories :
		nameOfCategories.append((x.id, x.name))
	form.subject.choices = nameOfCategories
	typeOfTimeDelta = []
	for x, y in app.config['TIMEDELTA_CHOICE'] :
		typeOfTimeDelta.append((x, y))
	form.timeDelta.choices = typeOfTimeDelta
	form.timeDelta.data = app.config['DEFAULT_TIME_DELTA']
	
	docs = models.Document.query.all()
	numberOfDocuments = len(docs)
	users = models.User.query.all()
	numberOfUser = len(users)
	
	listOfRecentDocument = models.Document.query.\
								limit(numberOfDocuments).from_self().\
								order_by(models.Document.timeStamp)
	listOfRecentDocument = list(listOfRecentDocument)
	resultlist = []
	for i in range(len(listOfRecentDocument) - 1, -1, -1) :
		doc = listOfRecentDocument[i]
		if doc.author.isAdmin :
			resultlist.append(doc)
			if len(resultlist) > 5 :
				break
	
	return render_template('frontend/index.html', 
							form = form,
							numberOfDocuments = numberOfDocuments,
							numberOfUser = numberOfUser,
							listOfRecentDocument = resultlist)
	
@frontend.route('/details')
@login_required
def details():
	uid = current_user.id
	u = models.User.query.filter(models.User.id == uid).first()
	docs = []
	for x in u.contributions :
		docs.append(x)
	doc = models.Document.query.filter(models.Document.id == u.lastVisit).first()
	
	return render_template('frontend/details.html', 
							titile = 'Home', 
							username = u.username, 
							docs = docs,
							doc = doc)

@frontend.route('/details/<int:uid>')
def otherUserDetails(uid):
	u = models.User.query.filter(models.User.id == uid).first()
	if u == None :
		flash(app.config['HOWDOYOUFINDTHISPAGE'])
		return redirect(url_for('frontend.index'))
	
	docs = []
	for x in u.contributions :
		docs.append(x)
	doc = models.Document.query.filter(models.Document.id == u.lastVisit).first()
	
	return render_template('frontend/details.html', 
							titile = 'Home', 
							username = u.username, 
							docs = docs,
							doc = doc)
	
@frontend.route('/FAQ', methods = ['POST', 'GET'])
def faq() :
	form = SuggestionForm()
	# print '#######\n\n\n\n  here'
	# print '###', form.suggestion.data
	return render_template('frontend/faq.html', form = form)

@frontend.route('/Thank', methods = ['POST', 'GET'])
def suggest() :
	flash('Having receive!!!')
	return render_template('frontend/index.html')

@frontend.route('/edit', methods = ['POST', 'GET'])
# @login_required
@fresh_login_required
def changeUserDetails() :
	user = current_user
	form = EditForm()
	u = models.User.query.filter(models.User.id == user.id).first()
	
	if not form.username.data :
		form.username.data = u.username
	if not form.email.data :
		form.email.data = u.email
	
	# print 'form.validate_on_submit:', form.validate_on_submit()
	if request.method == 'POST' and form.validate_on_submit() :
		# print 'xxxxxxx'
		if u.password == form.password.data :
			u.username = form.username.data
			print form.newPassword.data
			if len(form.newPassword.data) > 0 :
				u.password = form.newPassword.data
			u.email = form.email.data
			flash('Succefully change!!')
			db.session.commit()
			# print 'yyyyy'
			return redirect(url_for('frontend.changeUserDetails'))
		else :
			# print 'xxxxx'
			flash(app.config['PASSWROD_NOT_MATCH'])
	
	return render_template('frontend/changeUserDetails.html', form = form)

apps/views/loginpages.py
# -*- coding: utf-8 -*-

from flask import Flask, request, session, \
					g, redirect, url_for, \
					abort, render_template, flash,  \
					Blueprint, jsonify
from apps.forms import LoginForm
from flask.ext.login import login_user, logout_user, \
							current_user, login_required
from apps import lm, db, models, app
import rsa

loginpages = Blueprint('loginpages', __name__, 
					static_folder = 'static',
					template_folder = 'templates')

@loginpages.route('/_return_public')
def sendPublic() :
	ret = jsonify(publicKey = str(app.config['RSA_E']) \
					+ ' ' + \
				str(app.config['RSA_N']))
	return ret
					
def tryLogin(form) :
	username = form.username.data
	password = form.password.data
	print 'origin password:%s' % (password)
	password = rsa.core.decrypt_int(int(password), 
									int(app.config['RSA_D']), 
									int(app.config['RSA_N']))
	print 'password:%s' % (password)
	password = unicode(password)
	remember_me = form.remember_me.data
	u = models.User.query.filter_by(username = username)
	u = list(u)
	if len(u) < 1 :
		flash(app.config['FAIL_LOGIN'])
		return redirect(url_for('loginpages.login'))
	
	u = u[0]
	print 'u.password:%s' % (u.password)
	if cmp(u.password, password) != 0 :
		flash(app.config['FAIL_LOGIN'])
		return redirect(url_for('loginpages.login'))
	if 'remember_me' in session :
		session['remember_me'] = None
	login_user(u, remember = remember_me)
	g.user = current_user
	session['user'] = g.user.id
	flash(app.config['SUCCESS_LOGIN'])
	return redirect(request.args.get('next') or url_for('frontend.index'))

def checkAuthenticated(u) :
	if type(u.is_authenticated) == type(True) :
		return u.is_authenticated
	else :
		return u.is_authenticated()

	
@loginpages.before_request
def before_request():
	# print 'current_user:', current_user
	g.user = current_user
		
@loginpages.route('/login', methods=['GET', 'POST'])
def login() :
	# debug
	# if '_fresh' in session :
		# print session['_fresh']
	# print g.user
	# if 'user' in session : 
		# print session['user']
	# print 'user' in session
	
	# Have log in
	try :
		if 'user' in session and session['user'] == g.user.id :
			flash('you have been loggin in as %s.' % g.user.username)
			return redirect(url_for('frontend.index'))
	except Exception as e :
		pass
	
	form = LoginForm()
	if request.method == 'POST' and form.validate_on_submit():
		print 'form.password.data', form.password.data
		# flash('username: ' + form.username.data + '\n')
		# flash('remember_me : ' + str(form.remember_me.data) + '\n')
		return tryLogin(form)
	return render_template('loginpages/login.html', \
							title = 'Sign In', \
							form = form)	

@loginpages.route('/logout')
@login_required
def logout():
	session.pop('user', None)
	logout_user()
	return redirect(url_for('frontend.index'))

apps/views/viewproblems.py
# -*- coding: utf-8 -*-

from flask import Flask, request, session, \
					g, redirect, url_for, \
					abort, render_template, flash,  \
					Blueprint
from flask.ext.login import current_user, login_required
from apps import app, db, models
from apps.forms import SearchProblemForm, ProblemForm, BrushForm, ChoiceForm
import datetime
import flask.ext.whooshalchemy

processProblems = Blueprint('processProblems', __name__, 
					static_folder = 'static',
					template_folder = 'templates')

@processProblems.route('/search', methods=['GET', 'POST'])
def search() :
	if 'form' not in dir() :
		form = SearchProblemForm()
		categories = models.Subject.query.order_by('name')
		
		nameOfCategories = []
		for x in categories :
			nameOfCategories.append((x.id, x.name))
		form.subject.choices = nameOfCategories
		
		typeOfTimeDelta = []
		for x, y in app.config['TIMEDELTA_CHOICE'] :
			typeOfTimeDelta.append((x, y))
		form.timeDelta.choices = typeOfTimeDelta
		form.timeDelta.data = app.config['DEFAULT_TIME_DELTA']
	
	if request.method == 'POST' and form.validate_on_submit() :
		name = form.filename.data
		category = form.subject.data
		timeDelta = form.timeDelta.data
		print 'Good'
		return redirect(url_for('processProblems.showResult', category = category, 
							name = name, timeDelta = timeDelta))
		
	return render_template('processProblems/search.html', 
							title = u'Select your want!',
							form = form)

@processProblems.route('/show/<int:category>&<string:name>&<int:timeDelta>', methods = ['GET'])
def showResult(category, name, timeDelta) :
	timeDelta = app.config['TIMEDELTA'][timeDelta]
	startTime = datetime.datetime.utcnow() - timeDelta
	results = models.Document.query.\
					filter(models.Document.timeStamp >= startTime)\
					.whoosh_search(name, limit = 50).all()
	result = []
	for x in results :
		result.append((x.id, x.title))
	return render_template('processProblems/showresult.html', result = result)

def myValidate(arrayForm) :
	for pro in arrayForm :
		if not pro.validate_on_submit() :
			return False
		for choice in pro.choices :
			if not choice.validate_on_submit() :
				return False
	return True

def getAllProblem(doc) :
	allProblem = BrushForm()
	allProblem.pro = []
	count = 0
	allProblem.title = doc.title
	for x in doc.problems :
		count += 1
		# description = str(count) + u'、' + x.content.title()
		# Use ol/li to index the problems
		description = x.content.title()
		choices = x.choice.split(u'##')
		# print 'x.choice:', x.choice
		# print 'x.answer:', x.answer
		countChoice = 0
		pro = ProblemForm()
		pro.choices = []
		for y in choices :
			y = y.strip()
			if len(y) > 0 :
				option = chr(countChoice + ord('A'))
				choicesDescription = \
					option + \
					u'、' + unicode(y)
				
				thisChoice = ChoiceForm()
				thisChoice.option.default = False
				thisChoice.option.name = unicode(count)
				thisChoice.option.id = unicode(count)
				thisChoice.option.userValue = option
				thisChoice.description = unicode(choicesDescription)
				pro.choices.append(thisChoice)
				countChoice += 1
		pro.pid = x.id
		pro.index = count
		pro.description = description
		pro.check = 0
		allProblem.pro.append(pro)
	return allProblem

@processProblems.route('/show/<int:did>', methods = ['GET', 'POST'])
def show(did) :
	print 'yyyyyyyyyyyyyyyyyy'
	
	# print 'request.form:', request.form
	allCorret = False
	
	# 定义表格
	if 'allProblem' not in dir() :
		if did != 100 :
			doc = models.Document.query.filter(models.Document.id == did).first()
		else :
			doc = session['tempfile']
		allProblem = getAllProblem(doc)
	
	# 将传过来的表单填写入对应的表格位置
	if request.method == 'POST' :
		for pro in allProblem.pro :
			userChoices_list = request.form.getlist(str(pro.index))
			for c in userChoices_list :
				index = ord(c) - ord('A')
				# pro.choices[index].option.checked = True
				pro.choices[index].option.data = True
		# print request.Form['1']
	
	# 检查答案，给予反馈
	if allProblem.validate_on_submit() and myValidate(allProblem.pro) :
		allCorret = True
		for pro in allProblem.pro :
			userAnswer = unicode('')
			choiceIndex = 0
			for choice in pro.choices :
				# print choice.option.data
				if choice.option.data == True :
					userAnswer += unicode(chr(choiceIndex + ord('A')))
				choiceIndex += 1
			userAnswer = userAnswer.strip()
			# print pro.index, ':', userAnswer
			
			if len(userAnswer) < 1 :
				pro.check = 0
				allCorret = False
				continue
			
			realPro = models.Problem.query.filter(models.Problem.id == pro.pid)
			realPro = realPro.first()
			answer = unicode(realPro.answer)
			
			if userAnswer == answer :
				pro.check = 2
				pro.message = app.config['MESSAGE_FOR_RIGHT']
			else :
				pro.check = 1
				allCorret = False
				pro.message = app.config['MESSAGE_FOR_WRONG'] % (realPro.answer)
	
	print 'how allproblems:', 'allProblem' in dir()
	if allCorret == False :
		return render_template('processProblems/showproblems.html', 
								index = did, papers = allProblem)
	else :
		return render_template('processProblems/congratulation.html')

		
class MyOperateError(Exception) :
	description = ""

	def __init__(self, description = "Wrong in file!"):
		self.description = description
	
	def __repr__(self):
		return self.description
	
def change(x, documentType = 0) :
	# 0 -> 答案在括号中     1 -> 答案在全文最后
	if documentType == 0 :
		pat = re.compile(u'\r\n *[0-9]+[\.,、,．]')
		problems = pat.split(x)
		# print problems
		ret = []
		for pro in problems :
			if len(pro) < 3 :
				continue
			
			try :
			
				# Set the first letter in pro to be the answer
				# Get Answer from each problem
				getAnswer = False
				for reg in app.config['REGEX_ANSWER'] :
					pat = re.compile(reg)
					ansMatch = pat.search(pro)
					if ansMatch is None :
						continue
					getAnswer = True
					
					while True :
						next = pat.search(pro, ansMatch.end())
						if next is None :
							break
						ansMatch = next
					
					answer = ansMatch.group()
					answer = answer.strip()
					# print answer
					
					pat = re.compile(u'[\(（\)） ]')
					ans = pat.split(answer)
					answer = ''
					for i in range(0, len(ans)) :
						ans[i] = ans[i].strip()
						if len(ans[i]) > 0 :
							answer += ans[i]
					# print 'answer:', answer
					
					panDuanTi = False
					if answer in app.config['RIGHT_ANSWER'] or \
						answer in app.config['WRONG_ANSWER'] :
						if answer in app.config['RIGHT_ANSWER'] :
							answer = u'A'
						else :
							answer = u'B'
						panDuanTi = True
					
					pro = pro[:ansMatch.start()] + u'___' + pro[ansMatch.end():]
					
					break
				
				if getAnswer == False :
					print '\r\n\r\n Wrong here:', pro
					print '\r\n\r\n unicode here:', pro.decode('utf8')
					
					for reg in app.config['REGEX_ANSWER'] :
						pat = re.compile(reg)
						answer = pat.search(pro)
						print answer
					raise MyOperateError(u'No Answer in brackets.')
				
				if not panDuanTi :
					# Get choices
					# Choices must be set in the tail of the problem
					
					getChoice = False
					for reg in app.config['REGEX_CHOICE'] :
						pat = re.compile(reg, re.S)
						allChoices = pat.search(pro)
						if allChoices is None :
							continue
						getChoice = True
					allChoices = allChoices.group()
					# print 'allchoices:', allChoices
					pat = re.compile(app.config['REGEX_CHOICE_INDEX'])
					choice = pat.split(allChoices)
					choices = ""
					for x in choice :
						x = x.strip()
						if len(x) > 0 :
							choices += u'##' + x
					choices += u"##"
					# print choices
					
					# Get description from each problem
					ind = pro.index(allChoices)
					description = pro[0 : ind]
					description = description.strip()
				else :
					choices = u"##正确##错误##"
					description = pro
					# 题目描述已经处理，因为判断题无选项字段需要去除
				
				# 去除题目序号
				# 实际不需要？分开题目时已经去除？
				pat = re.compile(app.config['REGEX_PROBLEM_INDEX'])
				des = pat.match(description)
				
				try :
					des = des.group()
					description = description[len(des):]
				except Exception as e :
					description = description
				
				ret.append((description, choices, answer))
			except MyOperateError as e :
				print e.description
				raise MyOperateError(u'Unexpected Error.')
			except Exception as e :
				print e
				raise MyOperateError(u'Unexpected Error.')
		
		return ret


@processProblems.route('/upload', methods = ['GET', 'POST'])
@login_required
def upload() :
	if 'form' not in dir() :
		form = UploadForm()
		categories = models.Subject.query.order_by('name')
		nameOfCategories = []
		for x in categories :
			nameOfCategories.append((x.id, x.name))
		form.subject.choices = nameOfCategories
	
	
	# if 'form' in dir() :
		# print 'hhhhhhh'
		# print form.validate_on_submit()
		# print form.subject.data
		# print form.subject.choices
		# print form.filename.data
		# print form.file.data
		# print request.method
		# print form.errors
	
	if request.method == 'POST' :
		if form.validate_on_submit() :
			print "here"
			try :
				
				title = form.filename.data
				content = form.file.data
				category = form.subject.data
				
				print 'begin change'
				format_content = change(content)
				print 'end change'
	#			format_content should be a pair list
	#			the first element should be problem's description
	#			the second element should be problem's answer
				
				# print format_content
				# for x, y, z in format_content :
					# print x.encode('gb2312'), y.encode('gb2312'), z.encode('gb2312')
				
				if len(format_content) < 2 :
					raise MyOperateError('The number of problems is too small.')
				
				
				# print 'fine'
				
				if current_user.isAdmin == True :
					doc = models.Document(title = title, author = current_user, subjectId = category)
					db.session.add(doc)
					for content, choices, answer in format_content :
						pro = models.Problem(source = doc, content = content, choice = choices, answer = answer)
						db.session.add(pro)
					db.session.commit()
					flash(app.config['SUCCESS_UPLOAD'])
				else :
					flash(app.config['SUCCESS_PROCESS'])

apps/templates/flashMessage.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message|safe }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

apps/templates/layout.html
<!doctype html>
<html>
  <head>
    <meta http-equiv = "Content-Type" content = "text/html; charset=gb2312">
    <title>My Application</title>
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <a href = "{{url_for('index')}}"> Home </a> <br>
    <hr>
    {% if g.user.is_authenticated %}
    <div>
      User details
      <a href = "{{url_for('logout')}}"> Logtout </a>
    </div>
    <hr>
    {% endif %}
    {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul class=flashes>
      {% for message in messages %}
      <li> {{ message }}  </li>
      {% endfor %}
      </ul>
      {% endif %}
    {% endwith %}
    {% block body %}
    {% endblock %}
  </body>
</html>

apps/templates/mainpage.html
{% block doc -%}
  <!DOCTYPE html>
  <html{% block html_attribs %}{% endblock html_attribs %}>
  {%- block html %}
    <head>
      {%- block head %}
        <title>
          {% if title %}
            {{title|safe}}
          {% else %}
            刷题网
          {% endif %}
        </title>

        {%- block metas %}
          <!--[if lte IE 8]> 
            <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" />
          <![endif]--> 
          <meta http-equiv = "Content-Type" content = "text/html; charset=utf-8"/>
          <meta name = "viewport" content = "width=device-width, initial-scale=1.0"/>
        {%- endblock metas %}
        
        {%- block styles %}
          <!-- Bootstrap -->
          <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet" media="screen">
          <link href = "{{url_for('static', filename = 'css/myCSS.css')}}" rel = "stylesheet" media = "screen">
        {%- endblock styles %}
        
        {% block javascripts %}
          <script type=text/javascript>$SCRIPT_ROOT = {{ request.script_root|tojson|safe }};</script>
          <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
          <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
          <script type = "text/javascript" src = "{{url_for('static', filename = 'js/Barrett.js')}}"></script>
          <script type = "text/javascript" src = "{{url_for('static', filename = 'js/BigInt.js')}}"></script>
          <script type = "text/javascript" src = "{{url_for('static', filename = 'js/placeholder.js')}}"></script>
          <script type = "text/javascript" src = "{{url_for('static', filename = 'js/myJS.js')}}"></script>
          <script type = "text/javascript" src = "{{url_for('static', filename = 'js/myRightclick.js')}}"></script>
        {% endblock javascripts%}

      {%- endblock head %}
    </head>
    <body background = "{{url_for('static', filename = 'img/background1.png')}}" {% block body_attribs %}{% endblock body_attribs %}>
      {% block body -%}
        {% set authenticated = ('user' in session and session['user'] == current_user.id) %}
        <div id = "my-container-navbar" class = "container">
          <div id = "my-navbar" class = "navbar navbar-static-top">
            <div class = "navbar-inner">
              <ul class = "nav nav-tabs">
                {%if not authenticated %}
                  <li>
                    <a href = "{{ url_for('loginpages.login') }}">游客</a>
                  </li>
                {% endif %}
                <li>
                  <a href = "{{ url_for('frontend.index') }}">首页</a>
                </li>
                {% if authenticated == True %}
                  <li class = "dropdown">
                    <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown">
                      {{ current_user.username }}
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href = "{{ url_for('loginpages.logout')}}">登出</a>
                      </li>
                      <li>
                        <a href = "{{ url_for('frontend.details') }}">个人信息</a>
                      </li>
                      <li>
                        <a href = "{{ url_for('frontend.changeUserDetails') }}">修改信息</a>
                      </li>
                    </ul>
                  </li>
                  {% if current_user.isAdmin and current_user.isAdmin == True %}
                    <li>
                      <a href = "{{ url_for('processProblems.upload') }}">上传题目</a>
                    </li>
                    <li>
                      <a href = "{{ url_for('admin.index') }}">管理</a>
                    </li>
                  {% endif %}
                {% else %}
                  <li>
                    <a href = "{{ url_for('loginpages.login') }}">登入</a>
                  </li>
                  <li>
                    <a href = "{{ url_for('registerpages.register') }}">注册</a>
                  </li>
                {% endif %}
                {% if not (authenticated == True and current_user.isAdmin and current_user.isAdmin == True) %}
                  <li>
                    <a href = "{{ url_for('processProblems.upload') }}">处理题目</a>
                  </li>
                {% endif %}
                <li class = "pull-right">
                  <a href = "{{ url_for('processProblems.search') }}">搜索题目</a>
                </li>
              </ul>
            </div>
          </div>
          
        </div>
        
        <div id = "my-container-content" class = "container">
          {% include 'flashMessage.html' %}
          
          {% block someerrors %}
          {% endblock %}
          
          {% block content -%}
          {%- endblock content %}
            
          {% block otherNavbar %}
          {% endblock otherNavbar %}
        </div><br/>
        
        <div id = "my-footer" class = "container" align = "middle">
          <hr/>
          <p style = "font-size: 5px;">By -yzx</p><br/>
        </div>
        
      {%- endblock body %}
    </body>
  {%- endblock html %}
  </html>
{% endblock doc -%}