apps/views/frontend.py
from flask import Flask, Blueprint, render_template, \
					g, url_for, session, request, flash, \
					redirect
from flask.ext.login import login_required, \
					current_user, login_required,\
					fresh_login_required
from apps.forms import SuggestionForm, EditForm, SearchProblemForm
frontend = Blueprint('frontend', __name__, 
					static_folder = 'static',
					template_folder = 'templates')
from apps import models, app, db
					
@frontend.before_request
def before_request() :
	g.user = current_user
					
@frontend.route('/')
@frontend.route('/index/')
def index():
	# if '_fresh' in session :
		# print session['_fresh']
	# if 'user' in session : 
		# print session['user']
	
	form = SearchProblemForm()
	categories = models.Subject.query.order_by('name')
	nameOfCategories = []
	for x in categories :
		nameOfCategories.append((x.id, x.name))
	form.subject.choices = nameOfCategories
	typeOfTimeDelta = []
	for x, y in app.config['TIMEDELTA_CHOICE'] :
		typeOfTimeDelta.append((x, y))
	form.timeDelta.choices = typeOfTimeDelta
	form.timeDelta.data = app.config['DEFAULT_TIME_DELTA']
	
	docs = models.Document.query.all()
	numberOfDocuments = len(docs)
	users = models.User.query.all()
	numberOfUser = len(users)
	
	listOfRecentDocument = models.Document.query.\
								limit(numberOfDocuments).from_self().\
								order_by(models.Document.timeStamp)
	listOfRecentDocument = list(listOfRecentDocument)
	resultlist = []
	for i in range(len(listOfRecentDocument) - 1, -1, -1) :
		doc = listOfRecentDocument[i]
		if doc.author.isAdmin :
			resultlist.append(doc)
			if len(resultlist) > 5 :
				break
	
	return render_template('frontend/index.html', 
							form = form,
							numberOfDocuments = numberOfDocuments,
							numberOfUser = numberOfUser,
							listOfRecentDocument = resultlist)
	
@frontend.route('/details')
@login_required
def details():
	uid = current_user.id
	u = models.User.query.filter(models.User.id == uid).first()
	docs = []
	for x in u.contributions :
		docs.append(x)
	doc = models.Document.query.filter(models.Document.id == u.lastVisit).first()
	
	return render_template('frontend/details.html', 
							titile = 'Home', 
							username = u.username, 
							docs = docs,
							doc = doc)

@frontend.route('/details/<int:uid>')
def otherUserDetails(uid):
	u = models.User.query.filter(models.User.id == uid).first()
	if u == None :
		flash(app.config['HOWDOYOUFINDTHISPAGE'])
		return redirect(url_for('frontend.index'))
	
	docs = []
	for x in u.contributions :
		docs.append(x)
	doc = models.Document.query.filter(models.Document.id == u.lastVisit).first()
	
	return render_template('frontend/details.html', 
							titile = 'Home', 
							username = u.username, 
							docs = docs,
							doc = doc)
	
@frontend.route('/FAQ', methods = ['POST', 'GET'])
def faq() :
	form = SuggestionForm()
	# print '#######\n\n\n\n  here'
	# print '###', form.suggestion.data
	return render_template('frontend/faq.html', form = form)

@frontend.route('/Thank', methods = ['POST', 'GET'])
def suggest() :
	flash('Having receive!!!')
	return render_template('frontend/index.html')

@frontend.route('/edit', methods = ['POST', 'GET'])
# @login_required
@fresh_login_required
def changeUserDetails() :
	user = current_user
	form = EditForm()
	u = models.User.query.filter(models.User.id == user.id).first()
	
	if not form.username.data :
		form.username.data = u.username
	if not form.email.data :
		form.email.data = u.email
	
	# print 'form.validate_on_submit:', form.validate_on_submit()
	if request.method == 'POST' and form.validate_on_submit() :
		# print 'xxxxxxx'
		if u.password == form.password.data :
			u.username = form.username.data
			print form.newPassword.data
			if len(form.newPassword.data) > 0 :
				u.password = form.newPassword.data
			u.email = form.email.data
			flash('Succefully change!!')
			db.session.commit()
			# print 'yyyyy'
			return redirect(url_for('frontend.changeUserDetails'))
		else :
			# print 'xxxxx'
			flash(app.config['PASSWROD_NOT_MATCH'])
	
	return render_template('frontend/changeUserDetails.html', form = form)

apps/views/viewproblems.py
# -*- coding: utf-8 -*-

from flask import Flask, request, session, \
					g, redirect, url_for, \
					abort, render_template, flash,  \
					Blueprint
from flask.ext.login import current_user, login_required
from apps import app, db, models
from apps.forms import SearchProblemForm, ProblemForm, BrushForm, ChoiceForm
import datetime
import flask.ext.whooshalchemy

processProblems = Blueprint('processProblems', __name__, 
					static_folder = 'static',
					template_folder = 'templates')

@processProblems.route('/search', methods=['GET', 'POST'])
def search() :
	if 'form' not in dir() :
		form = SearchProblemForm()
		categories = models.Subject.query.order_by('name')
		
		nameOfCategories = []
		for x in categories :
			nameOfCategories.append((x.id, x.name))
		form.subject.choices = nameOfCategories
		
		typeOfTimeDelta = []
		for x, y in app.config['TIMEDELTA_CHOICE'] :
			typeOfTimeDelta.append((x, y))
		form.timeDelta.choices = typeOfTimeDelta
		form.timeDelta.data = app.config['DEFAULT_TIME_DELTA']
	
	if request.method == 'POST' and form.validate_on_submit() :
		name = form.filename.data
		category = form.subject.data
		timeDelta = form.timeDelta.data
		print 'Good'
		return redirect(url_for('processProblems.showResult', category = category, 
							name = name, timeDelta = timeDelta))
		
	return render_template('processProblems/search.html', 
							title = u'Select your want!',
							form = form)

@processProblems.route('/show/<int:category>&<string:name>&<int:timeDelta>', methods = ['GET'])
def showResult(category, name, timeDelta) :
	timeDelta = app.config['TIMEDELTA'][timeDelta]
	startTime = datetime.datetime.utcnow() - timeDelta
	results = models.Document.query.\
					filter(models.Document.timeStamp >= startTime)\
					.whoosh_search(name, limit = 50).all()
	result = []
	for x in results :
		result.append((x.id, x.title))
	return render_template('processProblems/showresult.html', result = result)

def myValidate(arrayForm) :
	for pro in arrayForm :
		if not pro.validate_on_submit() :
			return False
		for choice in pro.choices :
			if not choice.validate_on_submit() :
				return False
	return True

def getAllProblem(doc) :
	allProblem = BrushForm()
	allProblem.pro = []
	count = 0
	allProblem.title = doc.title
	for x in doc.problems :
		count += 1
		# description = str(count) + u'、' + x.content.title()
		# Use ol/li to index the problems
		description = x.content.title()
		choices = x.choice.split(u'##')
		# print 'x.choice:', x.choice
		# print 'x.answer:', x.answer
		countChoice = 0
		pro = ProblemForm()
		pro.choices = []
		for y in choices :
			y = y.strip()
			if len(y) > 0 :
				option = chr(countChoice + ord('A'))
				choicesDescription = \
					option + \
					u'、' + unicode(y)
				
				thisChoice = ChoiceForm()
				thisChoice.option.default = False
				thisChoice.option.name = unicode(count)
				thisChoice.option.id = unicode(count)
				thisChoice.option.userValue = option
				thisChoice.description = unicode(choicesDescription)
				pro.choices.append(thisChoice)
				countChoice += 1
		pro.pid = x.id
		pro.index = count
		pro.description = description
		pro.check = 0
		allProblem.pro.append(pro)
	return allProblem

@processProblems.route('/show/<int:did>', methods = ['GET', 'POST'])
def show(did) :
	print 'yyyyyyyyyyyyyyyyyy'
	
	# print 'request.form:', request.form
	allCorret = False
	
	# 定义表格
	if 'allProblem' not in dir() :
		if did != 100 :
			doc = models.Document.query.filter(models.Document.id == did).first()
		else :
			doc = session['tempfile']
		allProblem = getAllProblem(doc)
	
	# 将传过来的表单填写入对应的表格位置
	if request.method == 'POST' :
		for pro in allProblem.pro :
			userChoices_list = request.form.getlist(str(pro.index))
			for c in userChoices_list :
				index = ord(c) - ord('A')
				# pro.choices[index].option.checked = True
				pro.choices[index].option.data = True
		# print request.Form['1']
	
	# 检查答案，给予反馈
	if allProblem.validate_on_submit() and myValidate(allProblem.pro) :
		allCorret = True
		for pro in allProblem.pro :
			userAnswer = unicode('')
			choiceIndex = 0
			for choice in pro.choices :
				# print choice.option.data
				if choice.option.data == True :
					userAnswer += unicode(chr(choiceIndex + ord('A')))
				choiceIndex += 1
			userAnswer = userAnswer.strip()
			# print pro.index, ':', userAnswer
			
			if len(userAnswer) < 1 :
				pro.check = 0
				allCorret = False
				continue
			
			realPro = models.Problem.query.filter(models.Problem.id == pro.pid)
			realPro = realPro.first()
			answer = unicode(realPro.answer)
			
			if userAnswer == answer :
				pro.check = 2
				pro.message = app.config['MESSAGE_FOR_RIGHT']
			else :
				pro.check = 1
				allCorret = False
				pro.message = app.config['MESSAGE_FOR_WRONG'] % (realPro.answer)
	
	print 'how allproblems:', 'allProblem' in dir()
	if allCorret == False :
		return render_template('processProblems/showproblems.html', 
								index = did, papers = allProblem)
	else :
		return render_template('processProblems/congratulation.html')

		
class MyOperateError(Exception) :
	description = ""

	def __init__(self, description = "Wrong in file!"):
		self.description = description
	
	def __repr__(self):
		return self.description
	
def change(x, documentType = 0) :
	# 0 -> 答案在括号中     1 -> 答案在全文最后
	if documentType == 0 :
		pat = re.compile(u'\r\n *[0-9]+[\.,、,．]')
		problems = pat.split(x)
		# print problems
		ret = []
		for pro in problems :
			if len(pro) < 3 :
				continue
			
			try :
			
				# Set the first letter in pro to be the answer
				# Get Answer from each problem
				getAnswer = False
				for reg in app.config['REGEX_ANSWER'] :
					pat = re.compile(reg)
					ansMatch = pat.search(pro)
					if ansMatch is None :
						continue
					getAnswer = True
					
					while True :
						next = pat.search(pro, ansMatch.end())
						if next is None :
							break
						ansMatch = next
					
					answer = ansMatch.group()
					answer = answer.strip()
					# print answer
					
					pat = re.compile(u'[\(（\)） ]')
					ans = pat.split(answer)
					answer = ''
					for i in range(0, len(ans)) :
						ans[i] = ans[i].strip()
						if len(ans[i]) > 0 :
							answer += ans[i]
					# print 'answer:', answer
					
					panDuanTi = False
					if answer in app.config['RIGHT_ANSWER'] or \
						answer in app.config['WRONG_ANSWER'] :
						if answer in app.config['RIGHT_ANSWER'] :
							answer = u'A'
						else :
							answer = u'B'
						panDuanTi = True
					
					pro = pro[:ansMatch.start()] + u'___' + pro[ansMatch.end():]
					
					break
				
				if getAnswer == False :
					print '\r\n\r\n Wrong here:', pro
					print '\r\n\r\n unicode here:', pro.decode('utf8')
					
					for reg in app.config['REGEX_ANSWER'] :
						pat = re.compile(reg)
						answer = pat.search(pro)
						print answer
					raise MyOperateError(u'No Answer in brackets.')
				
				if not panDuanTi :
					# Get choices
					# Choices must be set in the tail of the problem
					
					getChoice = False
					for reg in app.config['REGEX_CHOICE'] :
						pat = re.compile(reg, re.S)
						allChoices = pat.search(pro)
						if allChoices is None :
							continue
						getChoice = True
					allChoices = allChoices.group()
					# print 'allchoices:', allChoices
					pat = re.compile(app.config['REGEX_CHOICE_INDEX'])
					choice = pat.split(allChoices)
					choices = ""
					for x in choice :
						x = x.strip()
						if len(x) > 0 :
							choices += u'##' + x
					choices += u"##"
					# print choices
					
					# Get description from each problem
					ind = pro.index(allChoices)
					description = pro[0 : ind]
					description = description.strip()
				else :
					choices = u"##正确##错误##"
					description = pro
					# 题目描述已经处理，因为判断题无选项字段需要去除
				
				# 去除题目序号
				# 实际不需要？分开题目时已经去除？
				pat = re.compile(app.config['REGEX_PROBLEM_INDEX'])
				des = pat.match(description)
				
				try :
					des = des.group()
					description = description[len(des):]
				except Exception as e :
					description = description
				
				ret.append((description, choices, answer))
			except MyOperateError as e :
				print e.description
				raise MyOperateError(u'Unexpected Error.')
			except Exception as e :
				print e
				raise MyOperateError(u'Unexpected Error.')
		
		return ret


@processProblems.route('/upload', methods = ['GET', 'POST'])
@login_required
def upload() :
	if 'form' not in dir() :
		form = UploadForm()
		categories = models.Subject.query.order_by('name')
		nameOfCategories = []
		for x in categories :
			nameOfCategories.append((x.id, x.name))
		form.subject.choices = nameOfCategories
	
	
	# if 'form' in dir() :
		# print 'hhhhhhh'
		# print form.validate_on_submit()
		# print form.subject.data
		# print form.subject.choices
		# print form.filename.data
		# print form.file.data
		# print request.method
		# print form.errors
	
	if request.method == 'POST' :
		if form.validate_on_submit() :
			print "here"
			try :
				
				title = form.filename.data
				content = form.file.data
				category = form.subject.data
				
				print 'begin change'
				format_content = change(content)
				print 'end change'
	#			format_content should be a pair list
	#			the first element should be problem's description
	#			the second element should be problem's answer
				
				# print format_content
				# for x, y, z in format_content :
					# print x.encode('gb2312'), y.encode('gb2312'), z.encode('gb2312')
				
				if len(format_content) < 2 :
					raise MyOperateError('The number of problems is too small.')
				
				
				# print 'fine'
				
				if current_user.isAdmin == True :
					doc = models.Document(title = title, author = current_user, subjectId = category)
					db.session.add(doc)
					for content, choices, answer in format_content :
						pro = models.Problem(source = doc, content = content, choice = choices, answer = answer)
						db.session.add(pro)
					db.session.commit()
					flash(app.config['SUCCESS_UPLOAD'])
				else :
					flash(app.config['SUCCESS_PROCESS'])

apps/templates/frontend/changeUserDetails.html
{% extends "mainpage.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block someerrors %}
  {% if form.errors %}
    <div>
      <p>有点错误：</p>
      {{wtf.form_errors(form, hiddens = "False")}}
    </div>
    <hr/>
  {% endif %}
{% endblock %}

{% block content %}
  <p>如果你不想修改某项信息，请留空或者不做修改，具体请根据表格格式进行选择。</p><br/>
  <form action = "{{ url_for('frontend.changeUserDetails') }}" method = "POST" name = "editform">
    {{ form.hidden_tag() }}
    <p>请输入用户名：{{ form.username|safe }}</p><br/>
    <p>请输入旧的密码，进行确认：{{ form.password|safe }}</p><br/>
    <p>请输入新密码：{{ form.newPassword|safe }}</p><br/>
    <p>请在此输入新密码：{{ form.confirm|safe }}</p><br/>
    <p>请输入邮箱地址：{{ form.email|safe }}</p><br/>
    {{ form.submit(value = "提交")|safe }}
  </form>
{% endblock %}

apps/templates/frontend/details.html
{% extends "mainpage.html" %}

{% block content %}
  <p>此用户共上传{{ docs.__len__()|safe}}份题目！</p>
  <div id = "my-user-details">
    <ul class = "list-group">
      {% for doc in docs %}
        <li class = "list-group-item" style = "width: 35%;">
          <a href = {{ url_for('processProblems.show', did = doc.id) }}>{{doc.title|safe}}</a><br/>
        </li>
      {% endfor %}
    </ul>
    {% if doc %}
      <p>他（她）最近在刷<a href = "url_for('processProblems.show', did = doc.id)">{{doc.title|safe}}。</a></p>
    {% else %}
      <p>他（她）最近没有刷题。</p>
    {% endif %}
  </div>
  <p>返回<a href="{{url_for('frontend.index')}}">首页</a>！</p>
{% endblock %}

apps/templates/frontend/faq.html
{% extends "mainpage.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block someerrors %}
  {% if form.errors %}
    <div>
      <p>有点错误：</p>
      {{wtf.form_errors(form, hiddens = "False")}}
    </div>
    <hr/>
  {% endif %}
{% endblock %}

{% block content %}
  <div>
    <p>通用的事项：</p>
    <ol style = "font-size: 15px;">
      <li>上传的题目只支持选择题和判断题。</li><br/>
      <li>上传的可识别的题目数量要求大于两道。</li><br/>
      <li>题目长度不少于3个字。</li><br/>
      <li>不可识别的题目将被忽略。</li><br/>
      <li>只有管理员才可以保存所有上传的题目，非管理员只能保存最后一次上传的题目。</li><br/>
    </ol><br/>
    <hr/>
    <p>关于答案在题目<b>中</b>的类型试卷的事项：</p><br/>
    <ol style = "font-size: 15px;">
      <li>将优先寻找括号内的答案符号。</li><br/>
      <li>其次是在行末尾的答案符号。</li><br/>
      <li>其次是最后一个“对”“错”的中文。</li><br/>
      <li>最后是最后一个可以识别的英文字母。</li><br/>
    </ol><br/>
    <hr/>
    <p>关于答案在题目<b>后</b>的类型试卷的事项：</p><br/>
    <ol style = "font-size: 15px;">
      <li>请保证题目易于识别，否则不保证题目匹配答案的成功率。</li><br/>
    </ol><br/>
    
  <div>
  
  <p>上述没有解决你的问题？</p>
  <form method = "POST" action = "{{ url_for('frontend.suggest') }}" name = "suggest">
    <hr/>
      {{form.suggestion(rows = 10, cols = 100, placeholder = "输入你的问题，我们将会反馈。")|safe}}<br/>
      {{form.submit(value = "提交")|safe}}
  </form>
{% endblock %}

apps/templates/frontend/index.html
{% extends "mainpage.html" %}


{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
  {{ super() }}
  {% set authenticated = ('user' in session and session['user'] == current_user.id) %}
  <div id = "my-index-jumbotron" class = "jumbotron">
    <h1>题目处理+刷题网</h1><br/>
    <p>这是一个能够处理题目，使其变成我们容易刷题的形式的网站。</p><br/>
    <p>网站能够支持大多数主流的试卷，并将其保存为利于刷题的形式。</p><br/>
    <p>最后一次提交的信息将被保存下来，即使中途离开也不必担心。</p><br/>
  </div>
  
  <div class = "row">
    <div class = "col-lg-4">
      <h2>统计</h2><br/>
      <p>共有：<b>{{numberOfDocuments|safe}}</b>份题目。</p><br/>
      <p>共有：<b>{{numberOfUser|safe}}</b>位用户。</p><br/>
    </div>
    
    <div class = "col-lg-4">
      <h2>最近上传的题目：</h2><br/>
      {% for doc in listOfRecentDocument %}
        <a href = "{{url_for('processProblems.show', did = doc.id)}}">{{doc.title|safe}}</a><br/>
      {% endfor %}
    </div>
    
    <div class = "col-lg-4">
      <h2>搜索：</h2><br/>
      <form action = "{{ url_for('processProblems.search') }}" method = "post" id = "login">
        {{ form.hidden_tag() }}
        <p>科目： {{ form.subject(class = "my-input-field")|safe }} </p>
        <p>文件名关键字：{{ form.filename(class = "my-input-field", placeholder = "不填将显示所有题目")|safe }}</p>
        <p>上传时间：{{ form.timeDelta(class = "my-input-field")|safe }}</p>
        {{ wtf.form_field(form.submit, value = "开始查找")|safe }}
      </form>
    </div>
  </div>
{% endblock %}